name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_run:
    name: Build and run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --verbose
      - name: Run solutions
        run: time ./target/release/advent_of_code_2022
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --verbose
      - name: Run clippy
        run: cargo clippy
      - name: Run fmt
        run: cargo fmt -- --check
  bench:
    name: Bench
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Build benchmarks
        run: cargo bench --no-run
      - name: Run benchmarks
        run: cargo bench -- -n
      - name: Upload benchmark result
        uses: actions/upload-artifact@v3
        with:
          name: benchmark
          path: target/criterion