on: [push, pull_request]
name: Advent of Code
env:
  CARGO_TERM_COLOR: always
jobs:
  cpp:
    strategy:
      matrix:
        year: [2015]
    name: C++ ${{ matrix.year }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Release
        working-directory: ./${{ matrix.year }}
      - run: make all
        working-directory: ./${{ matrix.year }}/build
      - run: ./build/aoc${{ matrix.year }}_test -fc
        working-directory: ./${{ matrix.year }}
      - run: ./build/aoc${{ matrix.year }}
        working-directory: ./${{ matrix.year }}
  rust:
    strategy:
      matrix:
        year: [2021, 2022]
    name: Rust ${{ matrix.year }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Build
        run: cargo build --release --verbose
        working-directory: ./${{ matrix.year }}
      - name: Run solutions
        run: time ./target/release/advent_of_code_${{ matrix.year }}
        working-directory: ./${{ matrix.year }}
      - name: Run tests
        run: cargo test --verbose
        working-directory: ./${{ matrix.year }}
      - name: Run clippy
        run: cargo clippy
        working-directory: ./${{ matrix.year }}
      - name: Run fmt
        run: cargo fmt -- --check
        working-directory: ./${{ matrix.year }}