on: [push, pull_request]
name: Test Advent of Code
jobs:
  test:
    name: Build and test C++
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Release
      - run: make all
        working-directory: ./build
      - run: ./aoc2015_test
        working-directory: ./build
      - run: ./aoc2015
        working-directory: ./build