on: [push, pull_request]
name: Test Advent of Code
jobs:
  test:
    name: Build and test C++
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make build
      - run: make test
      - run: make run